### PR TITLE
fix

### PR DESCRIPTION
**Pull request by para0x0dise**
We have to include the Rstrtmgr.lib to avoid any further failures.

### CODE REVIEW

**Comment by kevoreilly** [comment]
What failures are you talking about?!

**Comment by para0x0dise** [comment]
> What failures are you talking about?!

The task would have failed immediately if I hadn't included this library.

**Comment by kevoreilly** [comment]
I've tested the monitor with the hook, it works fine. The lib and header file are not necessary,  what makes you think otherwise?

**Comment by para0x0dise** [comment]
Hmm, then I think the issue is from my side. Sorry

**Pull request closed without merging**
