### PR TITLE
Updated docs

### PR DESCRIPTION
**Pull request by RazviOverflow**
Added brief description on how to compile and add new hooks.

### CODE REVIEW

**Comment by kevoreilly** [comment]
Hi Razvi, I appreciate the PR, however VS2017 is the current targeted version of Visual Studio. I am surprised you have been able to get it to compile with a newer version, which is great, but until the project is itself upgraded to a different compiler version, the documentation needs to reflect the current version.

**Comment by RazviOverflow** [comment]
Apparently VS2022 was able to _Retarget_ the project successfully. Feels like I just got lucky this time, this isn't usually the case.

**Comment by RazviOverflow** [comment]
However, I wonder whether VS2017 would be any different while importing the project. Maybe I'll give it a try later and update the docs accordingly.

**Comment by kevoreilly** [comment]
There is no need to retarget or import anything in VS2017 - it just works.

**Comment by kevoreilly** [comment]
Hi Razvi, just to let you know I have begun testing VS2022 and so far it seems to work flawlessly. If all the tests pass (as I now assume they will), I will be moving the project to this compiler version in a dedicated commit.

**Pull request merged**
