### PR TITLE
Initial IPv6 support

### PR DESCRIPTION
**Pull request by cccs-mog**
This allow functions which are using `get_ip_port` to support IPv6 IP and to not give invalid value when hooking a call to an IPv6 address.

### CODE REVIEW

**Comment by kevoreilly** [comment]
Looks interesting - have you any samples that call these apis?

I note that there is an ``extern`` for ``DebugOutput()`` yet the code uses ``DebuggerOutput()`` which is a distinct function intended for the debugger log, not the analysis log. But then again, we wouldn't want to leave in these debug comments in production if the hooks are working and well tested.

**Comment by cccs-mog** [comment]
Hi @kevoreilly, sorry for pushing the hook tracing which I think you are refering in this PR for the DebuggerOutput which is intentionnal at this point. Will create a separate one in due time. I do have samples for it but I am still in testing phase. 

Regarding this particular PR around IPv6, this have been tested and a lot of samples use the hooks which are modified. Happy to provide one if this help. It allow Capemon to display IPv6 in behavioral logs instead of giberish due to an invalid buffer.

**Comment by kevoreilly** [comment]
Alright, so this PR is on ice until you have done further testing, unless I have misunderstood.

Obviously, for me to merge this it has to be production ready, not in testing. Just let me know.

**Comment by cccs-mog** [comment]
Hi @kevoreilly, Sorry for the confusion,actually this PR is production ready IPv6 capacity is well tested and should work like a charm. 

The hook tracing which was pushed in a separate commit by mistake to this PR was not and will make a separate PR for it when ready. Hope that clarifies. (This was removed since)

**Comment by kevoreilly** [comment]
Right! Gotcha finally. Do you have a sample that will flex the intended code in this PR that I can use for testing?

**Comment by cccs-mog** [comment]
It is technically all the same structure, ie they all use the function `get_ip_port` so I created a test case for testing. Could provide also specific malware sample if needed. Thanks !

**Comment by kevoreilly** [comment]
Yes that is what I am asking for.

**Comment by cccs-kevin** [comment]
@kevoreilly do you want a malware sample specifically? Otherwise the source file for testing an ipv6 connection is found in the tests/ folder for this PR

**Comment by kevoreilly** [comment]
Aha - I had actually not spotted that. I'll compile that test - thanks!

**Comment by cccs-mog** [comment]
Were you able to test it out @kevoreilly ? Thanks

**Comment by kevoreilly** [comment]
Sorry I still haven't got around to testing this! I'll try and get to it soon.

**Comment by kevoreilly** [comment]
Thank you ❤️

**Pull request merged**
