### PR TITLE
add PostThreadMessageA/PostThreadMessageW

### PR DESCRIPTION
**Pull request by nblog**
add PostThreadMessageA/PostThreadMessageW

### CODE REVIEW

**Comment by kevoreilly** [comment]
Hi nblog, thank you for this PR. I'm interested to know if these are apis you have seen used by malware, and if so whether you have any samples that can be used for testing.

The code looks great, I will try the hooks against a test set and get them merged.

**Comment by nblog** [comment]
@kevoreilly hi, `PostThreadMessage` appears in the injector (e.g. http://www.rohitab.com/discuss/topic/43926-setwindowshookex-dll-injection-my-code-and-some-questions/), i don't know how to write a reasonable test, so I just simply test the HOOK, and mark the source [`here`](https://github.com/kevoreilly/capemon/pull/59/commits/07e7b98b71781b51ba354c7bb710abf269342ae9#diff-95f27230fa869f8c133cc8dccf99d849c3b1a16d438e1d03386baf54913032deR3).

**Comment by kevoreilly** [comment]
Thanks for the reference - one of the main purposes of the hooks in `hook_windows.c` is to trigger monitor injection into the target process in order to monitor it. For example, the `SendNotifyMessage` hooks call `our_GetWindowThreadProcessId` to determine the process id of the target process, and then call `ProcessMessage` with that pid which causes the monitor to be injected into the target process. So I think these hooks might also need similar code to ensure that injected processes are monitored.

In the absence of known malware samples doing this, I think compiling and testing the code posted on rohitab.com is the way forward in order to be able to test that the hooks work and allow monitoring of the target processes. I am happy to try and compile a working version, but it might take some time as I am so busy.

**Comment by kevoreilly** [comment]
Apologies for the delay - I tested the injection method, and it's good to have the hooks, although as noted a mechanism to monitor the injected process is still outstanding.

This will involve obtaining the process ID from the thread ID, then sending the appropriate message to the analyzer to follow the injection. I hope to add this functionality later but that's no reason not to merge these hooks.

Thanks for your contribution!

**Pull request merged**
