### PR TITLE
ci: push changes to capev2 repository

### PR DESCRIPTION
**Pull request by TheMythologist**
## CI changes to msbuild:
1) Build capemon on x64 and x86 windows systems
2) Pushes the built capemon.dll and capemon_x64.dll to artifacts
3) Download the artifacts
4) Upload them to github releases of this repository
5) Push the new DLLs to [CAPEv2 repository](https://github.com/kevoreilly/capev2)

# What you need to do @kevoreilly:

### CODE REVIEW

**Comment by TheMythologist** [comment]
@kevoreilly Could you enable running workflow for this PR so I can see if it achieves what we want thanks :)

**Comment by kevoreilly** [comment]
Running...

**Comment by TheMythologist** [comment]
Ready to be merged, let me know if you need me to change anything

**Comment by kevoreilly** [comment]
Not sure this is working...


publishToo many retries.
--
build (x64, x64)No files were found with the provided path: D:\a\capemon\capemon\Release\capemon.dll. No artifacts will be uploaded.
build (x86, Win32)No files were found with the provided path: D:\a\capemon\capemon\x64\Release\capemon_x64.dll. No artifacts will be uploaded.

Too many retries.
[build (x64, x64)](https://github.com/kevoreilly/capemon/runs/7009135640?check_suite_focus=true#step:6:10)
No files were found with the provided path: D:\a\capemon\capemon\Release\capemon.dll. No artifacts will be uploaded.
[build (x86, Win32)](https://github.com/kevoreilly/capemon/runs/7009135539?check_suite_focus=true#step:7:10)
No files were found with the provided path: D:\a\capemon\capemon\x64\Release\capemon_x64.dll. No artifacts will be uploaded.

**Comment by TheMythologist** [comment]
:( I'll look into it

**Comment by TheMythologist** [comment]
Oh the "No files were found" is expected, but what isn't working is https://github.com/kevoreilly/capemon/runs/7009180324?check_suite_focus=true

**Comment by TheMythologist** [comment]
Did you allow Github releases for this repository?

**Comment by TheMythologist** [comment]
Found the source of the error, check out #44 😃

**Comment by r0ny123** [comment]
Thanks for the fix @TheMythologist and @Kevoreilly did you set up the ssh keys as mentioned in https://github.com/kevoreilly/capemon/pull/43#issue-1272449889 cause the latest capemon DLLs are not getting pushed to [CAPEv2 repo](https://github.com/kevoreilly/CAPEv2/tree/master/analyzer/windows/dll).

**Pull request merged**
